/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FirmaContratoRouteImport } from './routes/firma-contrato'
import { Route as AvisoDePrivacidadRouteImport } from './routes/aviso-de-privacidad'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarFolioRouteImport } from './routes/validar.$folio'
import { Route as AuthenticatedTablasRouteImport } from './routes/_authenticated.tablas'
import { Route as AuthenticatedExpedientesRouteImport } from './routes/_authenticated.expedientes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated.contratos'
import { Route as AuthenticatedContratoManualRouteImport } from './routes/_authenticated.contrato-manual'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated.configuracion'

const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmaContratoRoute = FirmaContratoRouteImport.update({
  id: '/firma-contrato',
  path: '/firma-contrato',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDePrivacidadRoute = AvisoDePrivacidadRouteImport.update({
  id: '/aviso-de-privacidad',
  path: '/aviso-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarFolioRoute = ValidarFolioRouteImport.update({
  id: '/validar/$folio',
  path: '/validar/$folio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTablasRoute = AuthenticatedTablasRouteImport.update({
  id: '/tablas',
  path: '/tablas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpedientesRoute =
  AuthenticatedExpedientesRouteImport.update({
    id: '/expedientes',
    path: '/expedientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContratoManualRoute =
  AuthenticatedContratoManualRouteImport.update({
    id: '/contrato-manual',
    path: '/contrato-manual',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/firma-contrato': typeof FirmaContratoRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/contrato-manual': typeof AuthenticatedContratoManualRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expedientes': typeof AuthenticatedExpedientesRoute
  '/tablas': typeof AuthenticatedTablasRoute
  '/validar/$folio': typeof ValidarFolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/firma-contrato': typeof FirmaContratoRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/contrato-manual': typeof AuthenticatedContratoManualRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expedientes': typeof AuthenticatedExpedientesRoute
  '/tablas': typeof AuthenticatedTablasRoute
  '/validar/$folio': typeof ValidarFolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/firma-contrato': typeof FirmaContratoRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/contrato-manual': typeof AuthenticatedContratoManualRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expedientes': typeof AuthenticatedExpedientesRoute
  '/_authenticated/tablas': typeof AuthenticatedTablasRoute
  '/validar/$folio': typeof ValidarFolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-de-privacidad'
    | '/firma-contrato'
    | '/login'
    | '/sitemap.xml'
    | '/terminos-y-condiciones'
    | '/configuracion'
    | '/contrato-manual'
    | '/contratos'
    | '/dashboard'
    | '/expedientes'
    | '/tablas'
    | '/validar/$folio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-de-privacidad'
    | '/firma-contrato'
    | '/login'
    | '/sitemap.xml'
    | '/terminos-y-condiciones'
    | '/configuracion'
    | '/contrato-manual'
    | '/contratos'
    | '/dashboard'
    | '/expedientes'
    | '/tablas'
    | '/validar/$folio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aviso-de-privacidad'
    | '/firma-contrato'
    | '/login'
    | '/sitemap.xml'
    | '/terminos-y-condiciones'
    | '/_authenticated/configuracion'
    | '/_authenticated/contrato-manual'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/expedientes'
    | '/_authenticated/tablas'
    | '/validar/$folio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AvisoDePrivacidadRoute: typeof AvisoDePrivacidadRoute
  FirmaContratoRoute: typeof FirmaContratoRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  ValidarFolioRoute: typeof ValidarFolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firma-contrato': {
      id: '/firma-contrato'
      path: '/firma-contrato'
      fullPath: '/firma-contrato'
      preLoaderRoute: typeof FirmaContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-privacidad': {
      id: '/aviso-de-privacidad'
      path: '/aviso-de-privacidad'
      fullPath: '/aviso-de-privacidad'
      preLoaderRoute: typeof AvisoDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$folio': {
      id: '/validar/$folio'
      path: '/validar/$folio'
      fullPath: '/validar/$folio'
      preLoaderRoute: typeof ValidarFolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tablas': {
      id: '/_authenticated/tablas'
      path: '/tablas'
      fullPath: '/tablas'
      preLoaderRoute: typeof AuthenticatedTablasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expedientes': {
      id: '/_authenticated/expedientes'
      path: '/expedientes'
      fullPath: '/expedientes'
      preLoaderRoute: typeof AuthenticatedExpedientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contrato-manual': {
      id: '/_authenticated/contrato-manual'
      path: '/contrato-manual'
      fullPath: '/contrato-manual'
      preLoaderRoute: typeof AuthenticatedContratoManualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedContratoManualRoute: typeof AuthenticatedContratoManualRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpedientesRoute: typeof AuthenticatedExpedientesRoute
  AuthenticatedTablasRoute: typeof AuthenticatedTablasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedContratoManualRoute: AuthenticatedContratoManualRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpedientesRoute: AuthenticatedExpedientesRoute,
  AuthenticatedTablasRoute: AuthenticatedTablasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AvisoDePrivacidadRoute: AvisoDePrivacidadRoute,
  FirmaContratoRoute: FirmaContratoRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  ValidarFolioRoute: ValidarFolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
